# Generated by Django 5.0.7 on 2024-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId_int', models.IntegerField(verbose_name='item id')),
                ('itemName_text', models.CharField(max_length=20)),
                ('itemInfo_text', models.CharField(max_length=200)),
                ('itemPrice_int', models.IntegerField(verbose_name='item price')),
            ],
        ),
    ]
