# Generated by Django 5.1.1 on 2024-09-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGPT', '0002_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemInfo_text',
            field=models.CharField(max_length=500),
        ),
    ]
